<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE student [
    <!ELEMENT student (name+, age, fees )>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT standard (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT fees (#PCDATA)>
]>
<student>
    <name>Ali</name>
    <name>Ali</name>
    <age>23</age>
    
    <fees>8000</fees>
</student>