<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE student [
    <!ELEMENT student (name, age, (class|standard), fees)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT standard (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT fees (#PCDATA)>
]>
<student>
    <name>Ali</name>
    <age>23</age>
    <class>10</class>
    <fees>8000</fees>
</student>

